-- Inserção de pilhas de tecnologia (TechnologyStackEntity)
INSERT INTO stack (technology_name) VALUES
('Hibernate'),
('C#'),
('C++'),
('HTML'),
('CSS'),
('Node.js'),
('QuarKus'),
('MY SQL'),
('PostGreeSQL'),
('MOngoDB'),
('Docker'),
('JavaScript'),
('TypeScript'),
('Java'),
('SpringBoot'),
('JPA'),
('KAFKA'),
('Angular'),
('Flutter'),
('JDBC');